name: agriproduce
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # UI + Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  getwidget: ^5.0.0
  iconsax: ^0.0.8

  # State management
  flutter_riverpod: ^2.6.1

  # Networking + Storage
  http: ^1.2.2
  shared_preferences: ^2.3.5
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path_provider_android: ^2.2.15
  path: ^1.9.0
  get_storage: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Payments
  flutter_paystack: ^1.0.7

  # Utils
  intl: ^0.20.1
  uuid: ^4.5.1
  logger: ^2.5.0
  connectivity_plus: ^6.1.2
  csv: ^6.0.0
  open_file: ^3.5.10
  permission_handler: ^11.3.1
  file_picker: ^8.1.7
  url_launcher: ^6.3.1
  excel: ^4.0.6
  flutter_file_dialog: ^3.0.2

  # Notifications
  flutter_local_notifications: ^18.0.1

  # UI Animation / Effects
  flutter_staggered_animations: ^1.1.1
  skeleton_loader: ^2.0.0+4

  # PDF + Printing
  printing: ^5.13.4
  pdf: ^3.11.1

  # QR + Barcode
  qr_flutter: ^4.1.0
  qr: ^3.0.2

  # Search / Dropdown
  flutter_typeahead: ^5.2.0
  dropdown_search: ^6.0.1
  searchfield: ^1.2.1

  # Charts
  fl_chart: ^0.70.2

  # Speech
  speech_to_text: ^7.0.0

  # Sharing
  share_plus: ^10.1.4
  material_symbols_icons: ^4.2874.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/agriproducepayicon.png"

# Override intl version so it works with flutter_paystack
dependency_overrides:
  intl: ^0.20.1
  http: ^0.13.5

flutter:
  uses-material-design: true

  assets:
    - assets/splashscreen.png
    - assets/farmer.jpg
    - assets/newmarket.jpg
